### ISSUE TITLE
Wrong NestJS logo when choosing a starter

### ISSUE THREAD

**Issue by angelhdzmultimedia** [stackblitz/starters#7]
Wrong NestJS logo when choosing a starter

![image](https://github.com/stackblitz/starters/assets/10191085/7e130c6d-f534-4a6b-bad2-d21f6647fa0e)

But in the existing projects it's all good

![image](https://github.com/stackblitz/starters/assets/10191085/b550ac54-f99a-414b-97a8-8980fa93446f)

**Comment by angelhdzmultimedia** [comment]
### Update

I tried my best to sniff through all the repos to contribute with a pr, but apparently the NestJS logo ends hardcoded as SVG, something is confusing Nest with Next and the Next logo is used instead.

Went to the NestJS template https://github.com/stackblitz/template-nestjs
And the logo is OK!

https://github.com/stackblitz/template-nestjs/blob/master/logo.svg

**Comment by angelhdzmultimedia** [comment]
Can this be fixed?

**Comment by fvsch** [comment]
Fix is deploying right now. Sorry for the delay!

**Comment by angelhdzmultimedia** [comment]
> Fix is deploying right now. Sorry for the delay!

I so wanted to contribute haha😂, I was feeling powerless☹️ because after so many searches even in Google, didn't find the right place to do the fix myself haha. I'm glad that this is finally being solved, and that the beautiful NestJS logo is going to be shown in the starters dialog!

Wishing you all health, peace, and success! 🔥🎉❤️

**Comment by angelhdzmultimedia** [comment]
😊
![image](https://github.com/stackblitz/starters/assets/10191085/885408d1-e895-448f-a7d7-76bbff7c06e9)
